# Modelo para ETL

## Objetivos:

- Remover as colunas desnecessárias para a análise;
- Filtrar o dataset considerando somente o município de Curitiba e ensino fundamental;
- Tratamento de duplicatas e NAs;
- Comparação de dois anos consecutivos para criação da coluna target evasão.

Carregar a biblioteca Pandas

In [1]:
import pandas as pd

Carregar os dados do primeiro ano de análise, já filtrando as colunas de interesse

In [2]:
matr_2016 = pd.read_csv('MATRICULA_SUL_2016.CSV', sep='|', usecols=
                        ['CO_PESSOA_FISICA',
                        'NU_IDADE',
                        'TP_SEXO',
                        'TP_COR_RACA',
                        'TP_NACIONALIDADE',
                        'TP_ZONA_RESIDENCIAL',
                        'TP_OUTRO_LOCAL_AULA',
                        'IN_NECESSIDADE_ESPECIAL',
                        'IN_CEGUEIRA',
                        'IN_BAIXA_VISAO',
                        'IN_SURDEZ',
                        'IN_DEF_AUDITIVA',
                        'IN_SURDOCEGUEIRA',
                        'IN_DEF_FISICA',
                        'IN_DEF_INTELECTUAL',
                        'IN_DEF_MULTIPLA',
                        'IN_AUTISMO',
                        'IN_SINDROME_ASPERGER',
                        'IN_SINDROME_RETT',
                        'IN_TRANSTORNO_DI',
                        'IN_SUPERDOTACAO',
                        'TP_ETAPA_ENSINO',
                        'TP_UNIFICADA',
                        'TP_TIPO_TURMA',
                        'CO_ENTIDADE',
                        'TP_DEPENDENCIA',
                        'TP_LOCALIZACAO',
                        'CO_MUNICIPIO_END'])

Filtro para o município de Curitiba (cód 4106902)

In [3]:
matr_2016 = matr_2016.query('CO_MUNICIPIO_END == 4106902')

Filtro para ensino fundamental (1° a 7° série e 1° ao 8° ano)

In [4]:
filtro = [4, 5, 6, 7, 8, 9, 10, 14, 15, 16, 17, 18, 19, 20,
                21]

In [5]:
matr_2016 = matr_2016[matr_2016.TP_ETAPA_ENSINO.isin(filtro)]

Conferindo a dimensão resultante dos filtros

In [6]:
matr_2016.shape

(158201, 28)

Verificando registros duplicados

In [7]:
matr_2016[matr_2016.duplicated(subset='CO_PESSOA_FISICA', keep=False)]

,CO_PESSOA_FISICA,NU_IDADE,TP_SEXO,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_END,TP_ZONA_RESIDENCIAL,TP_OUTRO_LOCAL_AULA,IN_NECESSIDADE_ESPECIAL,IN_CEGUEIRA,...,IN_SINDROME_ASPERGER,IN_SINDROME_RETT,IN_TRANSTORNO_DI,IN_SUPERDOTACAO,TP_ETAPA_ENSINO,TP_UNIFICADA,TP_TIPO_TURMA,CO_ENTIDADE,TP_DEPENDENCIA,TP_LOCALIZACAO
406171,1.226126e+11,6.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41484827.0,4.0,1.0
439510,1.116861e+11,14.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,20.0,0.0,0.0,41374010.0,4.0,1.0
489838,1.196853e+11,11.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,18.0,0.0,0.0,41155815.0,4.0,1.0
492256,1.238796e+11,9.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41155815.0,4.0,1.0
496155,1.233683e+11,7.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41155815.0,4.0,1.0
693031,1.233683e+11,7.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41381068.0,4.0,1.0
700093,1.282340e+11,7.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41140176.0,3.0,2.0
834821,1.233240e+11,9.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41140419.0,3.0,1.0
842914,1.214567e+11,10.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41378555.0,3.0,1.0
911755,1.278751e+11,8.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41139909.0,3.0,1.0
955979,1.205224e+11,8.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41139542.0,3.0,1.0
1126972,1.261320e+11,6.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41123697.0,3.0,1.0
1127660,1.226754e+11,6.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41123697.0,3.0,1.0
1135963,1.214802e+11,9.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41124049.0,3.0,2.0
1777840,1.196853e+11,11.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,18.0,0.0,0.0,41135946.0,4.0,1.0
1937940,1.229699e+11,9.0,2.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,42016932.0,2.0,1.0
2290688,1.261248e+11,8.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,16.0,0.0,0.0,41369017.0,3.0,2.0
2339919,1.108559e+11,13.0,1.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,18.0,0.0,0.0,42144345.0,3.0,1.0
2553673,1.238600e+11,7.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,42114217.0,3.0,1.0
2918643,1.446920e+11,6.0,2.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,42020794.0,2.0,1.0
2961538,1.113181e+11,13.0,1.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,19.0,0.0,0.0,42069076.0,2.0,1.0
3144628,1.203311e+11,11.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,19.0,0.0,0.0,41041712.0,2.0,1.0
3531511,1.214167e+11,8.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41048555.0,3.0,1.0
3902036,1.125164e+11,12.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,20.0,0.0,0.0,41045548.0,2.0,1.0
3956478,1.108559e+11,13.0,1.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,20.0,0.0,0.0,41134400.0,4.0,1.0
4079661,1.242615e+11,7.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41136900.0,3.0,1.0
4095078,1.225354e+11,7.0,2.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41135954.0,3.0,1.0
5208937,1.220215e+11,9.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41123891.0,3.0,1.0
5377540,1.203311e+11,11.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,19.0,0.0,0.0,41131304.0,4.0,1.0
5594722,1.238796e+11,9.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41135865.0,4.0,1.0
5679457,1.225354e+11,7.0,2.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41379934.0,3.0,1.0
5774034,1.205224e+11,8.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41358864.0,3.0,1.0
5774882,1.446920e+11,6.0,2.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41384440.0,3.0,1.0
5777493,1.282340e+11,7.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41379900.0,3.0,1.0
5778722,1.214167e+11,8.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,16.0,0.0,0.0,41129466.0,3.0,1.0
5789965,1.226754e+11,6.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41385977.0,3.0,1.0
5955242,1.116861e+11,14.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,19.0,0.0,0.0,41131479.0,2.0,1.0
6004124,1.238600e+11,7.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41127315.0,3.0,1.0
6135875,1.214802e+11,9.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41130030.0,3.0,1.0
6178467,1.233240e+11,9.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41129121.0,3.0,1.0
6279309,1.229699e+11,9.0,2.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41405420.0,4.0,1.0
6321339,1.242615e+11,7.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41372875.0,3.0,1.0
6322279,1.261320e+11,6.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41129180.0,3.0,1.0
6331839,1.113181e+11,13.0,1.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,9.0,0.0,0.0,41127013.0,3.0,1.0
6340754,1.220215e+11,9.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41536894.0,3.0,1.0
6345201,1.226126e+11,6.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,14.0,0.0,0.0,41129903.0,3.0,1.0
6356524,1.278751e+11,8.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15.0,0.0,0.0,41132750.0,3.0,1.0
6359354,1.214567e+11,10.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,17.0,0.0,0.0,41131312.0,3.0,1.0
6363779,1.125164e+11,12.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,10.0,0.0,0.0,41131924.0,3.0,1.0
6377755,1.261248e+11,8.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,16.0,0.0,0.0,41374835.0,3.0,1.0

Como os registros duplicados representam uma quantidade muito pequena dos dados, optamos por fazer a remoção dessas linhas

In [8]:
matr_2016.drop_duplicates(subset=['CO_PESSOA_FISICA'], keep=False, inplace=True, ignore_index=True)

Dimensão final da tabela do primeiro ano de análise

In [9]:
matr_2016.shape

(158151, 28)

Recodificando os anos escolares para facilitar a análise posterior

In [10]:
matr_2016['TP_ETAPA_ENSINO'].replace(14, 1, inplace=True) # 1° ano
matr_2016['TP_ETAPA_ENSINO'].replace([4, 15], 2, inplace=True) # 2° ano
matr_2016['TP_ETAPA_ENSINO'].replace([5, 16], 3, inplace=True) # 3° ano
matr_2016['TP_ETAPA_ENSINO'].replace([6, 17], 4, inplace=True) # 4° ano
matr_2016['TP_ETAPA_ENSINO'].replace([7, 18], 5, inplace=True) # 5° ano
matr_2016['TP_ETAPA_ENSINO'].replace([8, 19], 6, inplace=True) # 6° ano
matr_2016['TP_ETAPA_ENSINO'].replace([9, 20], 7, inplace=True) # 7° ano
matr_2016['TP_ETAPA_ENSINO'].replace([10, 21], 8, inplace=True) # 8° ano
matr_2016['TP_ETAPA_ENSINO'].replace([11, 41], 9, inplace=True) # 9° ano

Carregando a base do segundo ano de análise

In [11]:
matr_2017 = pd.read_csv('MATRICULA_SUL_2017.CSV', sep='|', usecols=
                                ['CO_PESSOA_FISICA', 'TP_ETAPA_ENSINO'])

Filtrando para somente ensino fundamental

In [12]:
filtro2 = [4, 5, 6, 7, 8, 9, 10, 11, 14, 15, 16, 17, 18, 19, 20,
                21, 41]

In [13]:
matr_2017 = matr_2017[matr_2017.TP_ETAPA_ENSINO.isin(filtro2)]

Conferindo a dimensão da base de dados

In [14]:
matr_2017.shape

(3607211, 2)

Verificando duplicatas de alunos

In [15]:
matr_2017.sort_values(by='CO_PESSOA_FISICA', ignore_index=True, inplace=True)
matr_2017[matr_2017.duplicated(subset='CO_PESSOA_FISICA', keep=False)]

         CO_PESSOA_FISICA  TP_ETAPA_ENSINO
538          1.100213e+11             21.0
539          1.100213e+11             41.0
2840         1.100440e+11             21.0
2841         1.100440e+11             16.0
2913         1.100458e+11             21.0
...                   ...              ...
3562813      1.689465e+11             21.0
3569058      1.751953e+11             14.0
3569059      1.751953e+11             14.0
3570087      1.754354e+11             14.0
3570088      1.754354e+11             14.0

[3646 rows x 2 columns]

Remoção dos valores duplicados

In [16]:
matr_2017.drop_duplicates(subset=['CO_PESSOA_FISICA'], keep=False, inplace=True, ignore_index=True)

Recodificando os anos escolares para facilitar a análise posterior

In [17]:
matr_2017['TP_ETAPA_ENSINO'].replace(14, 1, inplace=True) # 1° ano
matr_2017['TP_ETAPA_ENSINO'].replace([4, 15], 2, inplace=True) # 2° ano
matr_2017['TP_ETAPA_ENSINO'].replace([5, 16], 3, inplace=True) # 3° ano
matr_2017['TP_ETAPA_ENSINO'].replace([6, 17], 4, inplace=True) # 4° ano
matr_2017['TP_ETAPA_ENSINO'].replace([7, 18], 5, inplace=True) # 5° ano
matr_2017['TP_ETAPA_ENSINO'].replace([8, 19], 6, inplace=True) # 6° ano
matr_2017['TP_ETAPA_ENSINO'].replace([9, 20], 7, inplace=True) # 7° ano
matr_2017['TP_ETAPA_ENSINO'].replace([10, 21], 8, inplace=True) # 8° ano
matr_2017['TP_ETAPA_ENSINO'].replace([11, 41], 9, inplace=True) # 9° ano

Unificando os datasets pelo código do aluno, usando o primeiro dataset como referência e renomeando as colunas com os anos respectivos

In [18]:
matr = pd.merge(matr_2016, matr_2017, how='left', on='CO_PESSOA_FISICA', suffixes=('', '_2017'))

Substituindo NA na etapa de ensino do segundo ano para zeros

In [19]:
matr.TP_ETAPA_ENSINO_2017.fillna(value=0, inplace=True)

Dimensão final do dataset (deve ser igual à dimensão do primeiro dataset tratado)

In [20]:
matr.shape

(158151, 29)

Verificando se sobraram duplicatas no dataset unificado

In [21]:
matr.sort_values(by='CO_PESSOA_FISICA', ignore_index=True, inplace=True)
matr[matr.duplicated(subset='CO_PESSOA_FISICA', keep=False)].shape

(0, 29)

Excluir as bases iniciais para aliviar a memória

In [22]:
del matr_2016
del matr_2017

Função lambda para classificação do status de cada aluno (repetente, evadido, aprovado ou erro)

In [23]:
matr['Status'] = matr.apply(lambda x: 'repetente' if (x['TP_ETAPA_ENSINO'] == x['TP_ETAPA_ENSINO_2017']) 
                            else ('aprovado' if x['TP_ETAPA_ENSINO_2017'] == x['TP_ETAPA_ENSINO']+1 
                                  else ('evadido' if x['TP_ETAPA_ENSINO_2017'] == 0 else 'erro')), axis=1)
matr.head()

,CO_PESSOA_FISICA,NU_IDADE,TP_SEXO,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_END,TP_ZONA_RESIDENCIAL,TP_OUTRO_LOCAL_AULA,IN_NECESSIDADE_ESPECIAL,IN_CEGUEIRA,...,IN_TRANSTORNO_DI,IN_SUPERDOTACAO,TP_ETAPA_ENSINO,TP_UNIFICADA,TP_TIPO_TURMA,CO_ENTIDADE,TP_DEPENDENCIA,TP_LOCALIZACAO,TP_ETAPA_ENSINO_2017,Status
0,1.100225e+11,12.0,2.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,7.0,0.0,0.0,41129180.0,3.0,1.0,7.0,repetente
1,1.100258e+11,13.0,2.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,8.0,0.0,0.0,41133005.0,4.0,1.0,9.0,aprovado
2,1.100260e+11,26.0,2.0,1.0,1.0,4106902.0,1.0,3.0,1.0,0.0,...,0.0,0.0,3.0,0.0,0.0,41146131.0,3.0,1.0,3.0,repetente
3,1.100260e+11,13.0,1.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,8.0,0.0,0.0,41130057.0,2.0,1.0,9.0,aprovado
4,1.100260e+11,15.0,2.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,8.0,0.0,0.0,41387279.0,2.0,1.0,0.0,evadido

Contagem de dados das categorias criadas acima

In [24]:
matr.value_counts(subset='Status')

Status
aprovado     129058
evadido       16630
repetente     11753
erro            710
dtype: int64

Valores classificados como erro são inconsistências dos dados que devem removidas da análise:
- Aluno que pulou 1 etapa de ensino;
- Aluno que regrediu etapa de ensino.

In [25]:
matr[matr.Status=='erro']

,CO_PESSOA_FISICA,NU_IDADE,TP_SEXO,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_END,TP_ZONA_RESIDENCIAL,TP_OUTRO_LOCAL_AULA,IN_NECESSIDADE_ESPECIAL,IN_CEGUEIRA,...,IN_TRANSTORNO_DI,IN_SUPERDOTACAO,TP_ETAPA_ENSINO,TP_UNIFICADA,TP_TIPO_TURMA,CO_ENTIDADE,TP_DEPENDENCIA,TP_LOCALIZACAO,TP_ETAPA_ENSINO_2017,Status
6,1.100260e+11,14.0,1.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,8.0,0.0,0.0,41146174.0,3.0,1.0,7.0,erro
107,1.100368e+11,12.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,5.0,0.0,0.0,41128370.0,4.0,1.0,7.0,erro
217,1.101017e+11,12.0,1.0,3.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,7.0,0.0,0.0,41129180.0,3.0,1.0,6.0,erro
357,1.101771e+11,13.0,1.0,1.0,1.0,4106902.0,1.0,3.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,41358830.0,3.0,1.0,5.0,erro
580,1.103016e+11,15.0,2.0,3.0,1.0,4106902.0,1.0,3.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,41131819.0,3.0,1.0,6.0,erro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147782,1.447284e+11,9.0,2.0,0.0,3.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,2.0,0.0,0.0,41152484.0,4.0,1.0,4.0,erro
147963,1.448118e+11,6.0,2.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,1.0,0.0,0.0,41129393.0,4.0,1.0,3.0,erro
148920,1.448338e+11,14.0,1.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,6.0,0.0,0.0,41127420.0,2.0,1.0,8.0,erro
155887,1.448410e+11,6.0,2.0,1.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,1.0,0.0,0.0,41533909.0,4.0,1.0,3.0,erro
157418,1.448565e+11,7.0,2.0,0.0,1.0,4106902.0,1.0,3.0,0.0,NaN,...,NaN,NaN,2.0,0.0,0.0,41130871.0,3.0,1.0,1.0,erro

Removendo as linhas com erros

In [26]:
matr = matr[matr.Status!='erro']

Conferindo o resultado final

In [27]:
matr.value_counts(subset='Status')

Status
aprovado     129058
evadido       16630
repetente     11753
dtype: int64

Removendo os dados do segundo ano e a coluna de município que não serão mias úteis.

In [28]:
matr.drop(columns=['CO_MUNICIPIO_END', 'TP_ETAPA_ENSINO_2017'], inplace=True)

Renomeando colunas para facilitar a análise posterior

In [29]:
matr.rename(columns={'CO_PESSOA_FISICA': 'ID',
                         'NU_IDADE': 'Idade',
                         'TP_SEXO': 'Sexo',
                         'TP_COR_RACA': 'Etnia',
                         'TP_NACIONALIDADE': 'Nacionalidade',
                         'TP_ZONA_RESIDENCIAL': 'Zona_res',
                         'TP_OUTRO_LOCAL_AULA': 'Outro_local_aula',
                         'IN_NECESSIDADE_ESPECIAL': 'Necessidade_especial',
                         'IN_CEGUEIRA': 'Cegueira',
                         'IN_BAIXA_VISAO': 'Baixa_visao',
                         'IN_SURDEZ': 'Surdez',
                         'IN_DEF_AUDITIVA': 'Def_auditiva',
                         'IN_SURDOCEGUEIRA': 'Surdocegueira',
                         'IN_DEF_FISICA': 'Def_fisica',
                         'IN_DEF_INTELECTUAL': 'Def_intelectual',
                         'IN_DEF_MULTIPLA': 'Def_multipla',
                         'IN_AUTISMO': 'Autismo',
                         'IN_SINDROME_ASPERGER': 'Asperger',
                         'IN_SINDROME_RETT': 'Rett',
                         'IN_TRANSTORNO_DI': 'Transtorno_DI',
                         'IN_SUPERDOTACAO': 'Superdotacao',
                         'TP_ETAPA_ENSINO': 'Etapa_ensino',
                         'TP_UNIFICADA': 'Unificada',
                         'TP_TIPO_TURMA': 'Tipo_turma',
                         'CO_ENTIDADE': 'ID_escola',
                         'TP_LOCALIZACAO': 'Localizacao',
                         'TP_DEPENDENCIA': 'Administracao'}, inplace=True)

Aplicando os labels nos dados codificados

In [30]:
matr.Sexo = matr.Sexo.map({1:'M', 2:'F'})
matr.Etnia = matr.Etnia.map({0:'Não Declarada', 1:'Branca', 2:'Preta', 3:'Parda', 4:'Amarela', 5:'Indígena'})
matr.Nacionalidade = matr.Nacionalidade.map({1:'Brasileiro', 2:'Naturalizado', 3:'Extrangeiro'})
matr.Zona_res = matr.Zona_res.map({1:'Urbana', 2:'Rural'})
matr.Outro_local_aula = matr.Outro_local_aula.map({1:'Hospital', 2:'Domicilio', 3:'Não recebe'})
matr.Unificada = matr.Unificada.map({0:'Não', 1:'Unificada', 2:'Multietapa', 3:'Multi', 4:'Correção de fluxo', 5:'Mista'})
matr.Tipo_turma = matr.Tipo_turma.map({0:'Não se aplica', 1:'Classe Hospitalar', 2:'Unidade Socioeducativa',
                                           3:'Unidade prisional', 4:'Atividade complementar', 5:'At educacional especializado'})
matr.Localizacao = matr.Localizacao.map({1:'Urbana', 2:'Rural'})
matr.Administracao = matr.Administracao.map({1:'Federal', 2:'Estadual', 3:'Municipal', 4:'Privada'})

As colunas de necessidade especial específicas deixaram de ser preenchidos quando o aluno não possui necessidade especial, também algumas linhas da etnia não tem informação.
Dessa maneira vamos preencher etnia como não declarada (valor 0) e as necessidades especiais também como ausentes (valor 0).

In [31]:
matr = matr.fillna(0)

Aplicando one hot encoding

In [32]:
matr = pd.get_dummies(matr, columns=
                        ['Sexo', 'Etnia', 'Nacionalidade', 'Zona_res', 'Outro_local_aula', 
                         'Unificada', 'Tipo_turma', 'Localizacao', 'Administracao'], 
                        drop_first=True)

Gerando arquivo CSV do resultado

In [33]:
matr.to_csv('evasão_16.csv')